all: Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8

Q1: lists.cpp
	g++ -Wall -o Q1 lists.cpp

Q2: Deque.cpp
	g++ -Wall -o Q2 Deque.cpp

Q3: WindGauge.h WindGauge.cpp testWindGauge.cpp
	g++ -Wall -o Q3 WindGauge.cpp testWindGauge.cpp

Q4: VectorReverse.cpp
	g++ -Wall -o Q4 VectorReverse.cpp

Q5: Lotto.cpp
	g++ -Wall -o Q5 Lotto.cpp

Q6: Access.h Access.cpp testAccess.cpp
	g++ -Wall -o Q6 Access.cpp testAccess.cpp

Q7: Maps.cpp
	g++ -Wall -o Q7 Maps.cpp

Q8: ./Bonus/Access.h ./Bonus/Access.cpp ./Bonus/testAccess.cpp
	cd Bonus
	g++ -Wall -o Q8 Access.cpp testAccess.cpp
	cd ..
