all: Q6 Q8

Q6: Access.h Access.cpp testAccess.cpp
	g++ -Wall -o Q6 Access.cpp testAccess.cpp

Q8: ./Bonus2/Access.h ./Bonus2/Access.cpp ./Bonus2/testAccess.cpp
	cd Bonus2
	g++ -Wall -o Q8 Access.cpp testAccess.cpp
	cd ..
