all: Q1 Q2 Q3 Q4 Q5

Q1: TempArrSearch.cpp
	g++ -Wall -o ArraySearch TempArrSearch.cpp

Q2: Stack.h testStack.cpp
	g++ -Wall -o Stack testStack.cpp

Q3: LinkedList.h testLinkedList.cpp
	g++ -Wall -o List testLinkedList.cpp

Q4: UseVectors.cpp
	g++ -Wall -o Vector1 UseVectors.cpp

Q5: UseVectors2.cpp
	g++ -Wall -o Vector2 UseVectors2.cpp